version: "2"

services:
  nginx:
    container_name: nginx
    image: nginx
    volumes:
      - "/tmp/nginx:/etc/nginx/conf.d"
      - "./html:/usr/share/nginx/html"
    ports:
      - "80:80"
    restart: always

  nginx-gen:
    container_name: nginx-gen
    image: jwilder/docker-gen
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "./templates:/etc/docker-gen/templates"
    volumes_from:
      - nginx
    links:
      - nginx
    depends_on:
      - nginx
    command: "-notify-sighup nginx -watch -only-exposed /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf"
    restart: always

networks:
  default:
    external:
      name: nginx_reverse_proxy_network
